const catalogo = [
    { name: 'avatar_1', image: 'img/avatar_1.jpg', time: new Date() },
    { name: 'avatar_3', image: 'img/avatar_2.jpg', time: new Date()},
    { name: 'avatar_2', image: 'img/avatar_3.jpg', time: new Date() },
    { name: 'avatar_4', image: 'img/avatar_4.jpg' , time: new Date()},
    { name: 'avatar_5', image: 'img/avatar_5.jpg', time: new Date() },
    { name: 'avatar_6', image: 'img/avatar_6.jpg', time: new Date() },
    { name: 'avatar_7', image: 'img/avatar_7.jpg' , time: new Date()},
    { name: 'avatar_9', image: 'img/avatar_8.jpg' , time: new Date()},
    { name: 'avatar_io', image: 'img/avatar_io.jpg', time: new Date() },
    { name: 'avatar_1', image: 'img/avatar_1.jpg', time: new Date()},
    { name: 'avatar_3', image: 'img/avatar_2.jpg', time: new Date() },
    { name: 'avatar_2', image: 'img/avatar_3.jpg' , time: new Date()},
    { name: 'avatar_4', image: 'img/avatar_4.jpg' , time: new Date()},
    { name: 'avatar_5', image: 'img/avatar_5.jpg' , time: new Date()},
    { name: 'avatar_6', image: 'img/avatar_6.jpg' , time: new Date()},
    { name: 'avatar_7', image: 'img/avatar_7.jpg' , time: new Date()},
    { name: 'avatar_9', image: 'img/avatar_8.jpg' , time: new Date()},
    { name: 'avatar_io', image: 'img/avatar_io.jpg' ,time: new Date()},
    { name: 'avatar_1', image: 'img/avatar_1.jpg', time: new Date()},
    { name: 'avatar_3', image: 'img/avatar_2.jpg' , time: new Date()},
    { name: 'avatar_2', image: 'img/avatar_3.jpg' , time: new Date()},
    { name: 'avatar_4', image: 'img/avatar_4.jpg' , time: new Date()},
    { name: 'avatar_5', image: 'img/avatar_5.jpg' , time: new Date()},
    { name: 'avatar_6', image: 'img/avatar_6.jpg' , time: new Date()},
    { name: 'avatar_7', image: 'img/avatar_7.jpg' , time: new Date()},
    { name: 'avatar_9', image: 'img/avatar_8.jpg' , time: new Date()},
    { name: 'avatar_io', image: 'img/avatar_io.jpg' , time: new Date()}
];
